export const list = [
  {
    customerName: 'Kevin Libovski',
    company: 'Microsoft',
    phone: '(208) 555-0121',
    email: 'kevinLibovski@gmail.com',
    country: 'Brazil',
    status: true,
  },
  {
    customerName: 'Kevin Libovski',
    company: 'Microsoft',
    phone: '(208) 555-0121',
    email: 'kevinLibovski@gmail.com',
    country: 'Brazil',
    status: false,
  },
  {
    customerName: 'Kevin Libovski',
    company: 'Microsoft',
    phone: '(208) 555-0121',
    email: 'kevinLibovski@gmail.com',
    country: 'Brazil',
    status: true,
  },
  {
    customerName: 'Kevin Libovski',
    company: 'Microsoft',
    phone: '(208) 555-0121',
    email: 'kevinLibovski@gmail.com',
    country: 'Brazil',
    status: true,
  },
  {
    customerName: 'Kevin Libovski',
    company: 'Microsoft',
    phone: '(208) 555-0121',
    email: 'kevinLibovski@gmail.com',
    country: 'Brazil',
    status: true,
  },
  {
    customerName: 'Kevin Libovski',
    company: 'Microsoft',
    phone: '(208) 555-0121',
    email: 'kevinLibovski@gmail.com',
    country: 'Brazil',
    status: true,
  },
  {
    customerName: 'Kevin Libovski',
    company: 'Microsoft',
    phone: '(208) 555-0121',
    email: 'kevinLibovski@gmail.com',
    country: 'Brazil',
    status: false,
  },
  {
    customerName: 'Kevin Libovski',
    company: 'Microsoft',
    phone: '(208) 555-0121',
    email: 'kevinLibovski@gmail.com',
    country: 'Brazil',
    status: false,
  },
];
